apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
description: Test Desc
foo: test
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item
        with:
          content: |
            - item1
            - item2    
  props-and-secrets:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Prop check
        shell: sh
        run: |
          echo "Directly from secrets context: secret: "
          expr substr "${{ secrets.secret1 }}" 1 1
          expr substr "${{ secrets.secret1 }}" 2 20
      - uses: docker://golang:1.20.3-alpine3.17
        name: Env check - properties set on step env
        shell: sh
        env:
          secret1: ${{secrets.secret1}}
        run: |
          echo "Made available as env variables too. secret: ''${secret1:0:2} ${secret1:2}'"             
